name: Download Templates by Legiz

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download mihomo-ru-bundle
        run: |
          curl -L "https://github.com/legiz-ru/remnawave-templates/raw/refs/heads/main/by-legiz/subscription-templates/mihomo-ru-bundle.yaml" \
          -o "templates/ru-bundle-by-legiz.yaml"         

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "legiz-ru@users.noreply.github.com"
          git config --local user.name "legiz-ru"
          git add templates/
          git commit -m "Update legiz templates" -a || echo "No changes to commit"
          git push
